### ISSUE TITLE
Warning when opening R file

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#114]
After an update I am getting the following errors/warnings:

When opening an R file:
Error detected while processing c:...windows.vim:

E108:No such variable : "s:path"
E103:  No such variable "s:p"

When trying to send a file to R:
Error detected while processing function SendFileToR

E115: Missing quote: '" because it already exists. Please, delete it.")
E116: Invalid arguments for function RWarningMsg

I am on windows 10 64 bit

**Comment by jalvesaq** [comment]
Please, in Normal mode, what is the output of:
```
:echo system("where gcc")
```
and
```
:echo $PATH
```

The variable s:path is created when the first `gcc` in $PATH is not in an `Rtools` directory. With the output of both commands above we can figure out what is going wrong.

I fixed the missing quote: https://github.com/jalvesaq/Nvim-R/commit/86366b70758019f80fe67ca2fda189c53101d808

**Comment by blayz3r** [comment]
:echo system("where gcc") gives:
c:\Rtools\gcc-4.6.3\bin\gcc.exe
c:\strawberry\c\bin\gcc.exe

Here is my path C:\ProgramData\Oracle\Java\javapath;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\Program Files\7-Zip;E:\Program Files\CMake\bin;E:\Program Files\Microsoft SQL Server\130\Tools\Binn\;E:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;E:\ProgramFiles\R\R-3.3.1\bin\x64;E:\ProgramFiles\Anaconda2;E:\ProgramFiles\Anaconda2\Scripts;E:\ProgramFiles\Anaconda2\Library\bin;E:\Program Files\Git\cmd;E:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;E:\Program Files (x86)\vim\vim80;C:\Users\XXX\.vim\bundle\Vundle.vim\autoload\ctags58;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;E:\ProgramData\chocolatey\bin;E:\ProgramFiles\eclipse\eclipse;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;E:\Program Files\Java\jdk1.8.0_101\bin;E:\ProgramFiles\eclipse\eclipse;E:\Program Files\nodejs\;C:\Users\XXX\AppData\Roaming\npm

Thanks for the lightning speed response btw!

**Comment by jalvesaq** [comment]
Thanks! Now I can see the bug. It was a simple mistake.

**Comment by blayz3r** [comment]
Thanks @jalvesaq, you run a tight ship

**Comment by polde-live** [comment]
Hi, I'm still getting this error on my Windows 7 machine, despite applying the patch:

:echo $PATH
```H:\app\zew_2_5443\product\12.1.0\client_1;H:\app\zew_2_5443\product\12.1.0\clien
t_1\bin;h:\oracle\product\11.2.0\client_1\bin;C:\Program Files\Common Files\Micr
osoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\W
indows Live;c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\Python27\;C:\Python27\Scrip
ts;C:\ProgramData\Oracle\Java\javapath;h:\oracle\product\11.1.0\client_1\bin;C:\
windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\Windows
PowerShell\v1.0\;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x
86)\Microsoft Application Virtualization Client;C:\Program Files\SAS\SharedFiles
(32)\Formats;"c:\Program Files (x86)\notepad++\";C:\Program Files\Microsoft SQL
Server\110\Tools\Binn\;c:\Python27\;H:\MinGW\bin;c:\Program Files (x86)\GnuWin32
\bin\;C:\Program Files (x86)\Windows Live\Shared;H:\Oracle\instantclient_11_2;H:
\oracle\instantclient_11_2;H:\Vim\vim80
```

:echo system("where gcc")
```
c:\Rtools\gcc-4.6.3\bin\gcc.exe
H:\MinGW\bin\gcc.exe
``
