### ISSUE TITLE
nvimcom failed to install on HPC

### ISSUE THREAD

**Issue by timedreamer** [jalvesaq/Nvim-R#454]
Hi,

 I was trying to install Nvim-R on a HPC environment. But I failed to install `nvimcom` (error message below). I think the error may be because it tried to write some file in the R installation directory which I don't have access.

 Any idea how to fix. 

Thank you so much!
Ji

```
  1 * installing to library ‘/home/jh6577/R/x86_64-centos-linux-gnu-library/3.6’
  2 * installing *source* package ‘nvimcom’ ...
  3 staged installation is only possible with locking
  4 ** using non-staged installation
  5 ** libs
  6 icc -std=gnu99 -I"/share/apps/r/3.6.0/intel/lib64/R/include" -DNDEBUG   -I/share/apps/r/3.6.0/intel/lib64/R/include -I/share/apps/pcre/8.39/intel/include -I/share/apps/jdk/1.8.0_111/inc
    lude  -fpic  -g -O2  -c nvimcom.c -o nvimcom.o
  7 nvimcom.c(946): warning #167: argument of type "void (*)()" is incompatible with parameter of type "void (*)(void *)"
  8       R_ToplevelExec(nvimcom_exec, NULL);
  9                      ^
 10
 11 icc -std=gnu99 -shared -L/share/apps/r/3.6.0/intel/lib64/R/lib -L/share/apps/pcre/8.39/intel/lib -L/share/apps/r/3.6.0/intel/lib64/R/lib -L/share/apps/intel/19.0.1/mkl/lib/intel64 -L/sh
    are/apps/jdk/1.8.0_111/lib -L/share/apps/intel/19.0.1/lib/intel64 -o nvimcom.so nvimcom.o -L/share/apps/r/3.6.0/intel/lib64/R/lib -lR
 12 (cd apps; make)
 13 make[1]: Entering directory `/state/partition1/job-6574958/RtmpAVWll4/R.INSTALL5cc4444af12a/nvimcom/src/apps'
 14 cc -pthread -std=gnu99 -O2 -Wall nclientserver.c -o nclientserver
 15 In file included from nclientserver.c:1:0:
 16 /usr/include/stdio.h:33:21: fatal error: stddef.h: No such file or directory
 17  # include <stddef.h>
 18                      ^
 19 compilation terminated.
 20 make[1]: *** [nclientserver] Error 1
 21 make[1]: Leaving directory `/state/partition1/job-6574958/RtmpAVWll4/R.INSTALL5cc4444af12a/nvimcom/src/apps'
 22 make: *** [nvimapps] Error 2

```

**Comment by jalvesaq** [comment]
Did you try setting the environment variable `R_LIBS_USER`?

**Comment by timedreamer** [comment]
I believe it's set to my home directory where I install other packages.

```r
> .libPaths()
[1] "/home/jh6577/R/x86_64-centos-linux-gnu-library/3.6"
[2] "/share/apps/r/3.6.0/intel/lib64/R/library"
> Sys.getenv("R_LIBS_USER")
[1] "~/R/x86_64-centos-linux-gnu-library/3.6"
```

**Comment by jalvesaq** [comment]
Looking with more attention to the output that you have posted, I noted this:

> /usr/include/stdio.h:33:21: fatal error: stddef.h: No such file or directory

That is, the problem seems to be missing headers of one of the most basic C libraries, the `stdio`.

**Comment by timedreamer** [comment]
Hi!

Thank you for looking into this. It's now fixed with `module unload gcc/6.3.0`. When I load R module `module load r/intel/3.6.0`. The `gcc/6.3.0` was also loaded. 

For some reason, I can't explain. When I unload the gcc, the `nvimcom` installed successfully. 

Thanks again for help! Great tool!
Ji

**Comment by jalvesaq** [comment]
Thank you for the feedback. The information might be useful for others with similar problems.

**Comment by VitorAguiar** [comment]
I have a similar problem, but in my case I get

`make[1]: cc: No such file or directory
`

Also, nvim-R installs nvimcom every time I open an R script. Maybe that's because I need to launch an interactive job to use R, which takes me to different computing machines every time. 

I tried to uninstall and install nvim-R again, but that doesn't fix it.

This is the whole message:

```
libPaths                                                                                                                                                                                                                            
['/home/ch229163/R/4.0.2/library', '/home/ch229163/R/4.0.2/library']
Why build nvimcom
nvimcom_home = ""
Required nvimcom
0.9-131
.libPaths()
Build_cmds
R CMD build "/home/ch229163/.vim/plugged/Nvim-R/R/nvimcom"
R CMD INSTALL --no-lock nvimcom_0.9-131.tar.gz
rm nvimcom_0.9-131.tar.gz
R --no-restore --no-save --slave -e "cat(installed.packages()['nvimcom', c('Version', 'LibPath', 'Built')], sep = '\n', file = '/home/ch229163/.cache/Nvim-R/nvimcom_info')"
RBuildErr
Warning:
 invalid uid value replaced by that for user 'nobody'
Warning:
 invalid gid value replaced by that for user 'nobody'

* installing to library ‘/home/ch229163/R/4.0.2/library’
* installing *source* package ‘nvimcom’ ...
staged installation is only possible with locking
** using non-staged installation
** libs
make[1]: cc: No such file or directory
make[1]: *** [Makefile:7: nclientserver] Error 127
make: *** [Makevars:9: nvimapps] Error 2 ERROR: compilation failed for package ‘nvimcom’
* removing ‘/home/ch229163/R/4.0.2/library/nvimcom’
Error in installed.packages()["nvimcom", c("Version", "LibPath", "Built")] :    subscript out of bounds Calls: cat
Execution halted
```
