### ISSUE TITLE
'Not Ready Yet'

### ISSUE THREAD

**Issue by RichardJActon** [jalvesaq/Nvim-R#499]
I'm having some install trouble in a new environment

I installed vim version 8.2.905 from source and i'm using R version 3.5.1. I installed Nvim-R with vim-plug which seemed to work fine.

Whenever I open vim and hit `\rf` I get: "Updating nvimcom... Building lists for omni completion... OK!" and the R terminal pane pops up which I can switch to and use but if I try to send a line from the editor to the terminal with `\l` or `\cc` etc. I get the message 'Not Ready yet'

In case it was a vim vs neovim issue I also installed neovim and the Nvim-R plugin in a separate plugin directory for neovim - I got the exact same issue, except after a bit I get the additional message: "The package nvimcom wasn't loaded yet. Please, quit R and try again."

I tried installing the latest nvimcom package from source and this shows up in my session info: nvimcom_0.9-92. Plus my `Sys.getenv("R_DEFAULT_PACKAGES")` includes nvimcom (both of these are from an R session opened when I hit \rf in vim/nvim so I seem to be getting the right R environment)

I'm a bit stumped any suggestions for fixing this?

**Comment by jalvesaq** [comment]
What is your operating system?

You can use the same directory to install the plugins for both Vim and Neovim via vim-plug.

**Comment by RichardJActon** [comment]
I believe that it is Redhat 6, my `lsb_release -a` gives me:

    Distributor ID: bullxServer
    Description:    bullx Linux Server release 6.3 (V1)
    Release:        6.3

I've also tried it from a simple ssh session and from within tmux - same behaviour

Yeah - i wasn't sure if the vim/nvim plugins would be OK together so I separated them just in case.
Thanks

**Comment by jalvesaq** [comment]
Any news on this issue?

**Comment by RichardJActon** [comment]
Hi I never figured it out - not had much time to spend trying to do so though

`:RDebugInfo` shows that:

`CMD_INSTALL` has this warning:

```
nvimcom.c(1163): warning #167: argument of type "void (*)()" is incompatible with parameter of type "void (*)(void)"
R_ToplevelExec(nvimcom_exec, NULL);
```

but the install appears to complete successfully

`CMD_build` has this warning:

```
* building ‘nvimcom_0.9-92.tar.gz’
Warning: invalid uid value replaced by that for user 'nobody'
```

The uid things might be an issue I wasn't sure what to do about it.

**Comment by jalvesaq** [comment]
It looks like your system does more strict checking than Ubuntu does. I have no problem or warning here, but looking at R source code I could see that indeed the function `nvimcom_exec` should have a void pointer as its only argument. Could you please try the branch https://github.com/jalvesaq/Nvim-R/tree/void_null ? It was derived from the stable branch since your nvimcom version is 0.9-92.

**Comment by RichardJActon** [comment]
I installed from the latest commit in the void_null branch: `remotes::install_github("jalvesaq/nvim-r@566cdb9a7e9c721df115d5662d62c42f28490058",subdir="R/nvimcom")` With the same result. 
The cluster i'm using has funky intel c/c++ compiler maybe that's the issue i'll see if I can persuade it to use gcc and see if that makes any difference.

**Comment by jalvesaq** [comment]
But at least this warning was fixed?

> nvimcom.c(1163): warning #167: argument of type "void (*)()" is incompatible with parameter of type "void (*)(void)"
> R_ToplevelExec(nvimcom_exec, NULL);

**Comment by RichardJActon** [comment]
Ah interesting. Whenever I start Nvim-R with `\rf` I get an `Updating nvimcom...` message and the `:RDebugInfo` gives me this:

```
CMD_INSTALL
* installing to library ‘/home/racton/Rlibs/3.5.1’
* installing *source* package ‘nvimcom’ ...
** libs
icc -I"/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/include" -DNDEBUG   -I/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/include   -fpic  -static-intel -fPIC -g -O2 -xSSE4.2 -fp-model precise -fp-model source  -c nvimcom.c -o nvimcom.o
nvimcom.c(1163): warning #167: argument of type "void (*)()" is incompatible with parameter of type "void (*)(void *)"
      R_ToplevelExec(nvimcom_exec, NULL);
                     ^

icc -shared -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/lib -g -O2 -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64 -L/usr/lib64/ -ltcl8.5 -ltk8.5 -lX11 -o nvimcom.so nvimcom.o -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/lib -lR
(cd apps; make)
make[1]: Entering directory `/scratch/racton/tmp/Rtmpl2PG8u/R.INSTALL2a40d704e02/nvimcom/src/apps'
icc -pthread -std=gnu99 -O2 -Wall nclientserver.c -o nclientserver
make[1]: Leaving directory `/scratch/racton/tmp/Rtmpl2PG8u/R.INSTALL2a40d704e02/nvimcom/src/apps'
installing via 'install.libs.R' to /home/racton/Rlibs/3.5.1/nvimcom
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (nvimcom)
libPaths
['/home/racton/Rlibs/3.5.1', '/home/racton/R/x86_64-pc-linux-gnu-library/3.5']
Start_nclientserver
StartR
Build_Omnils
> nvimcom:::nvim.buildomnils("datasets")
nvimcom R: omnils version is up to date: datasets 3.5.1
> nvimcom:::nvim.buildomnils("utils")
nvimcom R: omnils version is up to date: utils 3.5.1
> nvimcom:::nvim.buildomnils("grDevices")
nvimcom R: omnils version is up to date: grDevices 3.5.1
> nvimcom:::nvim.buildomnils("graphics")
nvimcom R: omnils version is up to date: graphics 3.5.1
> nvimcom:::nvim.buildomnils("stats")
nvimcom R: omnils version is up to date: stats 3.5.1
> nvimcom:::nvim.buildomnils("methods")
nvimcom R: omnils version is up to date: methods 3.5.1
> nvimcom:::nvim.buildomnils("nvimcom")
nvimcom R: omnils version is up to date: nvimcom 0.9-92
> nvimcom:::nvim.buildomnils("base")
nvimcom R: omnils version is up to date: base 3.5.1
>
.libPaths()
CMD_build
* checking for file ‘/home/racton/.vim/plugged/Nvim-R/R/nvimcom/DESCRIPTION’ ... OK
* preparing ‘nvimcom’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘nvimcom_0.9-92.tar.gz’
Warning: invalid uid value replaced by that for user 'nobody'
```

But installing nvimcom in an R session with:

```
remotes::install_github("jalvesaq/nvim-r@566cdb9a7e9c721df115d5662d62c42f28490058",subdir="R/nvimcom")
<9c721df115d5662d62c42f28490058",subdir="R/nvimcom")                         
Downloading GitHub repo jalvesaq/nvim-r@566cdb9a7e9c721df115d5662d62c42f28490058
✔  checking for file ‘/scratch/racton/tmp/RtmpdXqITg/remotes702f60e40c3f/jalvesaq-Nvim-R-566cdb9/R/nvimcom/DESCRIPTION’ (535ms)
─  preparing ‘nvimcom’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘nvimcom_0.9-92.2.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
   
Installing package into ‘/home/racton/Rlibs/3.5.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘nvimcom’ ...
** libs
icc -I"/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/include" -DNDEBUG   -I/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/include   -fpic  -static-intel -fPIC -g -O2 -xSSE4.2 -fp-model precise -fp-model source  -c nvimcom.c -o nvimcom.o
icc -shared -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/lib -g -O2 -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64 -L/usr/lib64/ -ltcl8.5 -ltk8.5 -lX11 -o nvimcom.so nvimcom.o -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/lib -lR
(cd apps; make)
make[1]: Entering directory `/scratch/racton/tmp/RtmpiTgIK6/R.INSTALLd9a7cf333d/nvimcom/src/apps'
icc -pthread -std=gnu99 -O2 -Wall nclientserver.c -o nclientserver
make[1]: Leaving directory `/scratch/racton/tmp/RtmpiTgIK6/R.INSTALLd9a7cf333d/nvimcom/src/apps'
installing via 'install.libs.R' to /home/racton/Rlibs/3.5.1/nvimcom
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (nvimcom)
```

It works without that void warning but it seems Nvim-R is not using the new version I installed for some reason

**Comment by jalvesaq** [comment]
You are still using the last released version of Nvim-R. If using [vim-plug](https://github.com/junegunn/vim-plug), you can try the `void_null` branch with this line in your vimrc:

```
Plug 'jalvesaq/Nvim-R', {'branch': 'void_null'}
```

If you confirm that the bug is fixed, I will merge the changes into the 'stable' branch.

**Comment by RichardJActon** [comment]
Oh yes, of course, forgot to update that - I can confirm that the void null warning is no longer being generated on the install:

```
CMD_INSTALL
* installing to library ‘/home/racton/Rlibs/3.5.1’
* installing *source* package ‘nvimcom’ ...
** libs
icc -I"/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/include" -DNDEBUG   -I/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/inc
lude   -fpic  -static-intel -fPIC -g -O2 -xSSE4.2 -fp-model precise -fp-model source  -c nvimcom.c -o nvimcom.o
icc -shared -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/lib -g -O2 -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64
 -L/usr/lib64/ -ltcl8.5 -ltk8.5 -lX11 -o nvimcom.so nvimcom.o -L/opt/rrzk/software/R/R-3.5.1_intel_mkl_parallel/lib64/R/lib -lR
(cd apps; make)
make[1]: Entering directory `/scratch/racton/tmp/Rtmpz5znv9/R.INSTALL14f66cf90c2a/nvimcom/src/apps'
icc -pthread -std=gnu99 -O2 -Wall nclientserver.c -o nclientserver
make[1]: Leaving directory `/scratch/racton/tmp/Rtmpz5znv9/R.INSTALL14f66cf90c2a/nvimcom/src/apps'
installing via 'install.libs.R' to /home/racton/Rlibs/3.5.1/nvimcom
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (nvimcom)
libPaths
['/home/racton/Rlibs/3.5.1', '/home/racton/R/x86_64-pc-linux-gnu-library/3.5']
Start_nclientserver
StartR
Build_Omnils
> nvimcom:::nvim.buildomnils("datasets")
nvimcom R: omnils version is up to date: datasets 3.5.1
> nvimcom:::nvim.buildomnils("utils")
nvimcom R: omnils version is up to date: utils 3.5.1
> nvimcom:::nvim.buildomnils("grDevices")
nvimcom R: omnils version is up to date: grDevices 3.5.1
> nvimcom:::nvim.buildomnils("graphics")
nvimcom R: omnils version is up to date: graphics 3.5.1
> nvimcom:::nvim.buildomnils("stats")
nvimcom R: omnils version is up to date: stats 3.5.1
> nvimcom:::nvim.buildomnils("methods")
nvimcom R: omnils version is up to date: methods 3.5.1
> nvimcom:::nvim.buildomnils("nvimcom")
nvimcom R: omnils is outdated: nvimcom (0.9-92 x 0.9-92.2)
Building files with lists of objects in loaded packages for omni completion and Object Browser...
> nvimcom:::nvim.buildomnils("base")
nvimcom R: omnils version is up to date: base 3.5.1
>
.libPaths()
CMD_build
* checking for file ‘/home/racton/.vim/plugged/Nvim-R/R/nvimcom/DESCRIPTION’ ... OK
* preparing ‘nvimcom’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘nvimcom_0.9-92.2.tar.gz’
Warning: invalid uid value replaced by that for user 'nobody'

The package nvimcom wasn't loaded yet. Please, quit R and try again.
```

But i'm still getting the 'nvimcom wasn't loaded yet', 'Not ready yet' issue and the `uid` warning.

**Comment by jalvesaq** [comment]
The uid warning seems to be harmless: https://stackoverflow.com/questions/30599326/warning-message-during-building-an-r-package-invalid-uid-value-replaced-by-that

**Comment by jalvesaq** [comment]
Nvimcom sends a message to Nvim-R through a datagram socket to `127.0.0.1` (localhost). This is an IPv4 address, and I don't know what happens if a system only supports IPv6. R and Vim must be in the same machine, otherwise, it's necessary to follow the procedures described in section _Options for accessing Remote R from local Vim_. I don't use R in remote machines, so the procedures described in this section may no longer work.

**Comment by RichardJActon** [comment]
Weird - I can send stuff over localhost at `127.0.0.1`  using `netcat` no problem, so It's not like the local network is completely blocked on the server or anything like that.
Thanks for the help.

**Comment by jalvesaq** [comment]
I deleted the `void_null` branch because I already merged its changes into both the `stable` and the `master` branches and because I have no other idea of what Nvim-R bug might be causing the issue in your system.

**Comment by jalvesaq** [comment]
I don't know what might be causing the problem, but why your home directory seems to be '/home/iago' and during `nvimcom` compilation R seems to be looking for something at '/home/jranke'?

**Comment by iago-pssjd** [comment]
Beyond that, if it is only used with `-ffile-prefix-map`, it may not be a problem (https://reproducible-builds.org/docs/build-path/, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70268)

**Comment by jalvesaq** [comment]
Looking again at this issue, I checked `nvimcom` code, and indeed the `help(` line was a spurious one, certainly added during debugging. I'm sorry for not noting this yesterday. The line is deleted now.

**Comment by jalvesaq** [comment]
Thanks for the feedback! I'm closing the issue, but you can reopen it or open a new one if the problem comes back.
