### ISSUE TITLE
Error in rout.vim: "Pattern delimiter not found" with complex R prompt

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#685]
When setting the following prompt, I am getting an error when launching Nvim-R inside Nvim:

```r
options(prompt = '\u1b[34m\uf101\u1b[0m ')
```

The error message is:

> E401: Pattern delimiter not found: /^^[[34m^[[0m.*/

The error occurs in line 92 of `rout.vim` but from my understanding there are multiple lines which could cause the error because they use an unescaped value of `g:Rout_prompt_str` (and `g:Rout_continue_str`) in regular expressions.

I should note that I have *not* set `g:Rout_prompt_str` manually, but it does have the value set inside `.Rprofile` so I'm assuming there's some logic to get it automatically from R.

(I am using Nvim-R 0.9.16 with NeoVim v0.7.2.)

**Comment by klmr** [comment]
Ah, there are more issues with this prompt. In particular, I am getting the following error when launching an R session via a custom launcher (with Platform LFS):

> ```
> Job <18449824> is submitted to default queue <interactive>.                                                                                                                                                    
> <<Waiting for dispatch ...>>
> <<Starting on rkanc023is01>>
> Bioconductor version '3.14' is out-of-date; the current release version '3.15'
>   is available with R version '4.2'; see https://bioconductor.org/install
> ^[[34m^[[0m nvimcom:::nvim.buildomnils("datasets")
> Error in !NvimcomEnv$isAscii : invalid argument type
> Calls: <Anonymous> ... GetFunDescription -> sapply -> lapply -> FUN -> CleanOmniLine
> Execution halted
> ```

**Comment by klmr** [comment]
The latter problem might not be related to the prompt after all, there seems to be some code executed before the ‘nvimcom’ package is correctly attached; consequently, adding `NvimcomEnv$isAscii <- FALSE` in line 12 of  `nvimcom/R/nvimcom.R` fixes this particular issue — however, this seems to have only been a symptom of a larger problem, since Nvim-R still seems to think ‘nvimcom’ isn’t loaded, even though it is. (For now I am blaming my LSF setup, apparently I am not allowed to SSH into the worker nodes. So maybe other ports that Nvim-R uses for communication are also closed?)

**Comment by jalvesaq** [comment]
The first issue should be fixed now if you define `Rout_prompt_str` in your `init.vim`.

**Comment by jalvesaq** [comment]
I'm sorry, but I can't replicate the second issue because I don't use the Platform LFS.

**Comment by klmr** [comment]
@jalvesaq Thanks for the prompt fix, and please ignore the second issue for now! I might create a new issue to track it, but I currently believe that the issue is our cluster setup, which simply blocks all communication between nodes except that happening directly via LSF.

**Comment by klmr** [comment]
Actually the error persists if I set `Rout_prompt_str` to the exact string of the prompt (in `init.lua`):

```lua
vim.g.Rout_prompt_str = "\x1b[34m\u{f101}\x1b[0m "
```

To make the error go away, I have to remove the ANSI escape codes, i.e.:

```lua
vim.g.Rout_prompt_str = "\u{f101} "
```

This isn’t clear from the documentation.

<details><summary>For completeness, here’s the complete error message with the original configuration</summary>

> ```
> Error detected while processing /home/rudolpk2/.local/share/nvim/site/pack/packer/opt/Nvim-R/syntax/rout.vim:
> line   92:
> E401: Pattern delimiter not found: /^^[[34m^[[0m .*/
> Error detected while processing /home/rudolpk2/.local/share/nvim/site/pack/packer/opt/Nvim-R/syntax/rout.vim:
> line   92:
> E475: Invalid argument: routInput /^^[[34m^[[0m .*/
> Error detected while processing function ROnJobStdout[17]..UpdateSynRhlist[11]..FunHiOtherBf:
> line    8:
> E5555: API call: Vim(syntax):E401: Pattern delimiter not found: /^^[[34m^[[0m .*/
> ```

</details>

(Incidentally, I’m using a [Nerd Font](https://www.nerdfonts.com/), the weird Unicode character is a right-pointing chevron.)

**Comment by jalvesaq** [comment]
I changed the documentation here (not committed yet) to:

```
When syntax highlighting .Rout files, Nvim-R considers "> " as the prompt
string and "+ " as the continuation string. If you have defined different
prompt and continuation strings in your `~/.Rprofile`, Nvim-R will try to get
them from R, but if they include special characters, you may have to
define them in your |vimrc| too to avoid errors and get them properly
highlighted. For example, if you have in your `~/.Rprofile`
>
   options(prompt = '\u1b[34m»\u1b[0m ')
<
you should put in your |vimrc|:
>
   let g:Rout_prompt_str = '»'
<
```
