### ISSUE TITLE
Sending lines to console shortly after opening leads to strange behavior

### ISSUE THREAD

**Issue by khughitt** [jalvesaq/Nvim-R#81]
This is an issue that has been coming up for a while now, but I wasn't quite sure what the cause was.

I can now at least reproduce the issue, so I thought I would report it in case you or others run into the same issue, or have any insights into what the origin of the issue might be.

**Problem**

When attempting to send lines to the R console very soon after opening the terminal, several anomalous things occur:
1. The console color changes (the white text set by colorout becomes green in my case..)
2. Vim enters insert mode and inserts a "0" at the start of the line
3. Attempting to send further lines (after returning to normal mode) results in similar behavior to 2. above.

Further, closing the console and reopening it does not fix the issue and it will continue to behave strangely until I fully exit nvim and start it again.

**To reproduce**
1. Open a .R/.Rmd/etc. file in nvim
2. Open a terminal `\rf`
3. Quickly (e.g. < 1s) send a line to the console

**Example**:

![nvim-r-console-bug](https://cloud.githubusercontent.com/assets/125001/16495111/faa8a25c-3eb9-11e6-94c5-23780f535424.gif)

**System info**
- Linux 64-bit
- NVIM v0.1.5-527-g57b56e3
- R 3.3.1

**Comment by jalvesaq** [comment]
Thanks for reporting the issue! When you sent the first command to R, Nvim-R asked nvimcom whether colorout and setwidth were loaded or not. When you sent the command too quickly, the `search()` command (run in the background) was not listing "colorout". Consequently, Nvim-R decided to syntax highlight the R Console.

I believe the bug is fixed now, unless you have `library(nvimcom)` in your .Rprofile and it is placed before `library(colorout)`: https://github.com/jalvesaq/Nvim-R/commit/978ebc02541d9aa2eeeee86a937c0d9e5eabb031

See also:
```vim
:h R_hl_term
:h R_setwidth
```
I recommend the use of setwidth. Indeed, I may add the code of setwidth into nvimcom in the future. But the syntax highlighting of R Console has both advantages and disadvantages over colorout, and it's a matter of taste choosing either one.

**Comment by khughitt** [comment]
Thanks for looking into this so quickly! Indeed it looks like the commit fixed the issue.

I also added `let R_hl_term = 0` to my init.vim to ensure that colorout is used, which I definitely prefer over the default coloring - thanks for the suggestion.

Regarding `R_setwidth`, it seems like Neovim does a good job handling the terminal width (aside from a clipping issue which I will report separately.)

However, adding `let R_setwidth = 1` to my init.vim leads to the strange insert-mode and 0 insertion behavior described above, even if the commands are not run right away, so this could be a problem if other users attempt to set this to 1.

**Comment by khughitt** [comment]
Looks like a possible regression bug with latest version of NVim-R (commit a61da55).

Issue now occurs _always_, regardless of how soon commands are sent to console.

Version info:
- NVIM v0.2.0-27-g01f1028
- R 3.3.2
- nvimcom 0.9-25

**Comment by jalvesaq** [comment]
Sorry, but I can't reproduce the bug. When I try to send a command immediately after starting R, I get the warning "Not ready yet". My system is the same as yours:
NVIM v0.2.0-104-g5f02608
R 3.3.2
nvimcom 0.9.25

**Comment by khughitt** [comment]
Strange.. Checked a few more things but the issue persists:

- Updated Neovim to NVIM v0.2.0-104-g5f02608
- Disabled all other plugins except for Nvim-R
- Tested in alternate terminals (urxvt, termite, xterm)
- Tested with .R and .Rmd files

It seems like it should be related to this earlier issue since the behavior (inserting a "0" at the start of the line and entering INSERT mode) is the same.

I'll let you know if I'm able to narrow down the cause of the issue any further.

Thanks for looking into it!

**Comment by jalvesaq** [comment]
Perhaps the regression was caused by this: https://github.com/jalvesaq/Nvim-R/commit/7e9aa20517c0b6cab71a44da941fd109621fa907

**Comment by khughitt** [comment]
Looks like that is the culprit -- I checked out 208e8fae13c8e4c7ad679f9a03d6a0caf0b25b29 and the issue went away.

I dropped setwidth from my Rprofile, but issue still occurs with most recent commit.

**Comment by jalvesaq** [comment]
I can't fix the bug because I can't reproduce it, but putting this in the vimrc should avoid it:
```vim
let R_setwidth = 0
```
Or this:
```vim
let R_setwidth = 0
let R_hl_term = 0
```

**Comment by khughitt** [comment]
Thanks @jalvesaq! The work-around appears to have done the trick.

Things are a bit busy this semester, but if I can find some time over the break, perhaps I'll see if I can track down the underlying cause of the issue.
